#!/usr/bin/env bash

brew_prefix=$(brew --prefix)

for tap in $(cat $HOME/.dotfiles/hooks/taps); do
  brew tap $tap 2>/dev/null
done

for pkg in $(cat $HOME/.dotfiles/hooks/packages); do
  if ! [ -d "$brew_prefix/opt/$pkg" ]; then
    brew install $pkg 2>/dev/null
  fi
done

for cask in $(cat $HOME/.dotfiles/hooks/casks); do
  if ! [ -d "/opt/homebrew-cask/Caskroom/$cask/" ]; then
    brew cask install $cask
  fi
done

bash_location=/usr/local/bin/bash
if ! grep -q $bash_location /etc/shells; then
  echo "Setting $bash_location as default shell..."
  echo $bash_location | sudo tee -a /etc/shells > /dev/null
  chsh -s $bash_location
fi
